FROM ghcr.io/fergusfettes/boxkit:latest

RUN git clone https://github.com/fergusfettes/minihf /distrobox/dotfiles
RUN apk update && \
    apk upgrade && \
    pip3 install --upgrade pip && \
    grep -v '^#' /pip-packages | xargs pip3 install
RUN rm /pip-packages
