FROM ghcr.io/fergusfettes/boxkit:latest



COPY pip-packages /
RUN apk update && \
    apk upgrade && \
    pip3 install --upgrade pip && \
    grep -v '^#' /pip-packages | xargs pip3 install
RUN rm /pip-packages
