FROM ghcr.io/fergusfettes/boxkit:latest

RUN git clone https://github.com/fergusfettes/minihf /distrobox/minihf
RUN \
     apk update && \
     apk upgrade && \
     . /venv/bin/activate && \
     pip install -r /distrobox/minihf/requirements.txt
